# Generated by Django 4.2 on 2024-12-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('speaker', models.CharField(max_length=254)),
                ('when', models.DateTimeField()),
                ('registration_open', models.BooleanField(default=False)),
                ('participants', models.ManyToManyField(related_name='event', to='profiles.userprofile')),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
    ]
