# Generated by Django 4.2 on 2024-12-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options_article_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-date_of_publication']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
