# Generated by Django 4.2 on 2024-12-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_user'),
        ('blog', '0003_alter_recipe_options_recipe_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_articles', models.ManyToManyField(blank=True, to='blog.article')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_list', to='profiles.userprofile')),
            ],
        ),
    ]
