# Generated by Django 4.2 on 2024-12-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_user'),
        ('blog', '0004_reading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'verbose_name_plural': 'Favourite articles'},
        ),
        migrations.CreateModel(
            name='FavouriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_recipes', models.ManyToManyField(blank=True, to='blog.recipe')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_list', to='profiles.userprofile')),
            ],
        ),
    ]
