# Generated by Django 4.2 on 2024-12-28 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_user'),
        ('blog', '0005_alter_reading_options_favouriterecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriterecipe',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fav_recipe_list', to='profiles.userprofile'),
        ),
    ]
