# Generated by Django 4.2 on 2024-12-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img1', models.ImageField(blank=True, null=True, upload_to='')),
                ('name_banner_img1', models.CharField(default='Banner image number one', max_length=254)),
                ('banner_img2', models.ImageField(blank=True, null=True, upload_to='')),
                ('name_banner_img2', models.CharField(default='Banner image number two', max_length=254)),
                ('banner_img3', models.ImageField(blank=True, null=True, upload_to='')),
                ('name_banner_img3', models.CharField(default='Banner image number three', max_length=254)),
                ('banner_img4', models.ImageField(blank=True, null=True, upload_to='')),
                ('name_banner_img4', models.CharField(default='Banner image number four', max_length=254)),
            ],
        ),
    ]
