# Generated by Django 4.2 on 2024-12-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='carousel',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
