# Generated by Django 4.2 on 2025-01-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carousel_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
