# Generated by Django 4.2 on 2024-12-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
