# Generated by Django 4.2 on 2024-12-18 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_email_and_more'),
        ('products', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='favourite_product',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='favourite_products',
            field=models.ManyToManyField(to='products.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='profiles.userprofile'),
        ),
    ]
