# Generated by Django 4.2 on 2024-12-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_wishlist_options_remove_wishlist_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='favourite_products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
