# Generated by Django 4.2 on 2024-12-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_image_primary_img_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
